apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: example-client
spec:
  grantTypes:
    - authorization_code
    - refresh_token
    - client_credentials
  redirectUris:
    - http://localhost:5555/callback
  secretName: example-client-secret
  scope: openid, profile, email
  tokenEndpointAuthMethod: client_secret_post
